<?php
$inicio=date('Y-m-01');$fim=date('Y-m-t');$iAnt=date('Y-m-01',strtotime('first day of last month'));$fAnt=date('Y-m-t',strtotime('last day of last month'));
$receitas=cpTotalPeriodo($pdo,'receitas','data_receita',$usuarioId,$inicio,$fim);$despesas=cpTotalPeriodo($pdo,'despesas','data_despesa',$usuarioId,$inicio,$fim);$despesasAnt=cpTotalPeriodo($pdo,'despesas','data_despesa',$usuarioId,$iAnt,$fAnt);$resultado=$receitas-$despesas;$saldo=cpSaldoGeral($pdo,$usuarioId);$taxa=$receitas>0?round($resultado/$receitas*100,1):null;
$stmt=$pdo->prepare('SELECT limite_gastos_mensal FROM usuarios WHERE id=:uid');$stmt->execute(['uid'=>$usuarioId]);$limite=$stmt->fetchColumn();$limite=$limite!==false&&$limite!==null?(float)$limite:null;
$diasRestantes=max(1,(int)date('t')-(int)date('j')+1);$disponivel=$limite!==null?max(0,$limite-$despesas):max(0,$resultado);$porDia=$disponivel/$diasRestantes;
$mensal=cpDadosMensais($pdo,$usuarioId,12);$diario=cpDadosDiariosMes($pdo,$usuarioId);$cats=cpCategoriasDespesas($pdo,$usuarioId,$inicio,$fim,4);
$radar=[];$varDesp=$despesasAnt>0?(($despesas-$despesasAnt)/$despesasAnt*100):null;if($varDesp!==null&&$varDesp>15)$radar[]=['nivel'=>'amarelo','titulo'=>'Gastos acima do ritmo','mensagem'=>'Suas despesas cresceram '.number_format($varDesp,1).'% em relação ao mês anterior.'];if($resultado<0)$radar[]=['nivel'=>'vermelho','titulo'=>'Mês no negativo','mensagem'=>'As despesas superam as receitas em '.formatarMoeda(abs($resultado)).'.'];if($limite!==null&&$despesas>$limite)$radar[]=['nivel'=>'vermelho','titulo'=>'Limite mensal ultrapassado','mensagem'=>'Você passou seu limite de gastos em '.formatarMoeda($despesas-$limite).'.'];if($cats){$totalC=array_sum(array_map(fn($x)=>(float)$x['total'],$cats));$top=$cats[0];$pct=$totalC>0?(float)$top['total']/$totalC*100:0;if($pct>=35)$radar[]=['nivel'=>'amarelo','titulo'=>'Gastos concentrados em '.$top['categoria'],'mensagem'=>$top['categoria'].' representa '.number_format($pct,0).'% das principais despesas do mês ('.formatarMoeda((float)$top['total']).').'];}if($receitas>0&&$resultado/$receitas>=.2)$radar[]=['nivel'=>'verde','titulo'=>'Boa folga no mês','mensagem'=>'Seu resultado positivo equivale a '.number_format($resultado/$receitas*100,0).'% das receitas atuais.'];
$stmt=$pdo->prepare("(SELECT 'receita' tipo,descricao,valor,data_receita data FROM receitas WHERE usuario_id=:a) UNION ALL (SELECT 'despesa' tipo,descricao,valor,data_despesa data FROM despesas WHERE usuario_id=:b) ORDER BY data DESC LIMIT 7");$stmt->execute(['a'=>$usuarioId,'b'=>$usuarioId]);$movs=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT titulo,valor_meta,valor_atual FROM metas WHERE usuario_id=:uid AND concluida=0 ORDER BY prazo IS NULL,prazo ASC LIMIT 3');$stmt->execute(['uid'=>$usuarioId]);$metas=$stmt->fetchAll();
?>
<div class="topo-pagina"><div><span class="eyebrow">VISÃO PESSOAL</span><h1>Olá, <?=limpar(explode(' ',usuarioLogadoNome())[0])?> 👋</h1><p>Entenda seu mês, seu ritmo de gastos e os próximos passos.</p></div><button type="button" class="btn btn-secundario" data-copiloto-pergunta="Explique meu mês de forma simples e diga o principal ponto de atenção.">Explicar meu mês</button></div>
<div class="grade-resumo dashboard-pf-resumo">
<?php $metricas=[['Saldo geral',$saldo,$saldo>=0?'positivo':'negativo','Tudo que entrou menos tudo que saiu desde o início.'],['Receitas do mês',$receitas,'positivo','Total de entradas do mês atual.'],['Despesas do mês',$despesas,'negativo','Total de saídas do mês atual.'],['Resultado do mês',$resultado,$resultado>=0?'positivo':'negativo','O que restou das receitas após as despesas.']];foreach($metricas as $i=>$m):?><button class="cartao cartao-metrica metrica-interativa" type="button" data-detalhe="pfdet<?=$i?>"><div class="rotulo"><?=limpar($m[0])?></div><div class="valor <?=$m[2]?>"><?=formatarMoeda((float)$m[1])?></div><div class="variacao">Entender →</div><div class="metrica-detalhe" id="pfdet<?=$i?>" hidden><?=limpar($m[3])?></div></button><?php endforeach;?>
</div>
<div class="grade-dupla grade-pf-inteligencia">
<div class="cartao"><div class="cabecalho-grafico"><div><h3>Receitas x Despesas</h3><p class="secao-ajuda">Em 1M, o gráfico mostra a movimentação diária do mês atual.</p></div><div class="periodos-grafico"><button class="periodo ativo" data-meses="1">1M</button><button class="periodo" data-meses="3">3M</button><button class="periodo" data-meses="6">6M</button><button class="periodo" data-meses="12">12M</button></div></div><div class="container-grafico"><canvas id="graficoEvolucao"></canvas></div></div>
<div class="cartao radar-card"><div class="radar-titulo"><div><h3>RadarPilot</h3><p class="secao-ajuda">O que merece sua atenção agora.</p></div><span class="radar-badge">● ativo</span></div><div class="radar-lista"><?php if(!$radar):?><p class="texto-vazio">Registre movimentações para ativar os alertas.</p><?php else:foreach(array_slice($radar,0,5) as $r):?><div class="radar-item <?=limpar($r['nivel'])?>"><span class="radar-dot"></span><div class="radar-conteudo"><strong><?=limpar($r['titulo']??ucfirst($r['nivel']))?></strong><p><?=limpar($r['mensagem'])?></p><button class="radar-acao" type="button" data-copiloto-pergunta="Explique este alerta e sugira uma ação possível: <?=limpar($r['mensagem'])?>">Entender e agir →</button></div></div><?php endforeach;endif;?></div></div>
</div>
<div class="grade-tripla pf-planejamento">
<div class="cartao"><span class="eyebrow">ORÇAMENTO</span><h3>Quanto ainda posso gastar?</h3><div class="numero-destaque"><?=formatarMoeda($disponivel)?></div><p class="secao-ajuda"><?=$limite!==null?'Considerando seu limite mensal configurado.':'Estimativa usando o resultado atual do mês.'?></p><div class="pf-diario"><span>Ritmo diário sugerido</span><strong><?=formatarMoeda($porDia)?>/dia</strong></div><a href="perfil.php" class="link-limpar">Ajustar limite</a></div>
<div class="cartao"><span class="eyebrow">CONCENTRAÇÃO</span><h3>Onde seu dinheiro foi</h3><?php if(!$cats):?><p class="texto-vazio">Sem despesas no mês.</p><?php else:$totalCats=array_sum(array_map(fn($x)=>(float)$x['total'],$cats));foreach($cats as $c):$pct=$totalCats>0?(float)$c['total']/$totalCats*100:0;?><div class="mini-categoria"><span><?=limpar($c['categoria'])?></span><strong><?=number_format($pct,0)?>%</strong></div><?php endforeach;endif;?><a href="relatorios.php" class="link-limpar">Abrir relatório</a></div>
<div class="cartao"><span class="eyebrow">METAS</span><h3>Seu próximo objetivo</h3><?php if(!$metas):?><p class="texto-vazio">Você ainda não possui metas em andamento.</p><a href="metas.php" class="btn btn-secundario btn-bloco">Criar uma meta</a><?php else:$m=$metas[0];$p=$m['valor_meta']>0?min(100,$m['valor_atual']/$m['valor_meta']*100):0;?><strong><?=limpar($m['titulo'])?></strong><div class="barra-progresso" style="margin-top:12px"><div class="preenchido" style="width:<?=$p?>%"></div></div><p class="secao-ajuda" style="margin-top:8px"><?=number_format($p,0)?>% concluída</p><a href="metas.php" class="link-limpar">Ver todas as metas</a><?php endif;?></div>
</div>
<div class="cartao" style="margin-top:20px"><div class="radar-titulo"><h3>Últimas movimentações</h3><div><a href="receitas.php" class="link-limpar">Receitas</a> · <a href="despesas.php" class="link-limpar">Despesas</a></div></div><?php if(!$movs):?><p class="texto-vazio">Nenhuma movimentação registrada.</p><?php else:?><div class="tabela-responsiva"><table><tbody><?php foreach($movs as $m):?><tr><td><?=limpar($m['descricao'])?></td><td><?=date('d/m',strtotime($m['data']))?></td><td class="<?=$m['tipo']==='receita'?'positivo':'negativo'?>" style="text-align:right"><?=$m['tipo']==='receita'?'+':'-'?> <?=formatarMoeda((float)$m['valor'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
<script src="../assets/js/dashboard.js"></script><script>inicializarGraficoEvolucao({mensal:<?=json_encode($mensal,JSON_UNESCAPED_UNICODE)?>,diario:<?=json_encode($diario,JSON_UNESCAPED_UNICODE)?>});</script>
