<?php
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../database/conexao.php';require_once __DIR__.'/../includes/negocio_financeiro.php';exigirLogin();if(usuarioLogadoTipo()!=='mei'){header('Location: dashboard.php');exit;}
$tituloPagina='Negócio';$pdo=conectar();$uid=usuarioLogadoId();cpSincronizarCustosRecorrentesMes($pdo,$uid);
$stmt=$pdo->prepare('SELECT nome,nicho FROM usuarios WHERE id=:uid');$stmt->execute(['uid'=>$uid]);$usuario=$stmt->fetch();
try{$stmt=$pdo->prepare('SELECT * FROM perfil_negocio WHERE usuario_id=:uid');$stmt->execute(['uid'=>$uid]);$perfil=$stmt->fetch()?:[];$stmt=$pdo->prepare('SELECT * FROM produtos_servicos WHERE usuario_id=:uid AND ativo=1 ORDER BY tipo,nome');$stmt->execute(['uid'=>$uid]);$itens=$stmt->fetchAll();$stmt=$pdo->prepare('SELECT * FROM funcionarios WHERE usuario_id=:uid AND ativo=1 ORDER BY nome');$stmt->execute(['uid'=>$uid]);$funcionarios=$stmt->fetchAll();$stmt=$pdo->prepare('SELECT * FROM fornecedores WHERE usuario_id=:uid AND ativo=1 ORDER BY nome');$stmt->execute(['uid'=>$uid]);$fornecedores=$stmt->fetchAll();$stmt=$pdo->prepare('SELECT * FROM custos_negocio WHERE usuario_id=:uid AND ativo=1 ORDER BY recorrente DESC,descricao');$stmt->execute(['uid'=>$uid]);$custos=$stmt->fetchAll();}catch(Throwable $e){$perfil=[];$itens=[];$funcionarios=[];$fornecedores=[];$custos=[];}
$comp=cpCompromissosMensais($pdo,$uid);$msg=$_SESSION['mensagem_negocio']??null;unset($_SESSION['mensagem_negocio']);
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/navbar.php';
?>
<div class="topo-pagina"><div><span class="eyebrow">GESTÃO DO NEGÓCIO</span><h1>Estrutura do empreendimento</h1><p>Produtos, equipe, fornecedores e custos alimentam automaticamente o dashboard e o Copiloto.</p></div><a href="dashboard.php" class="btn btn-secundario">← Voltar ao dashboard</a></div>
<?php if($msg):?><div class="alerta-mensagem sucesso"><?=limpar($msg)?></div><?php endif;?>
<div class="cartao negocio-resumo"><div><span>Compromissos recorrentes</span><strong><?=formatarMoeda($comp['total'])?>/mês</strong></div><div><span>Equipe</span><strong><?=formatarMoeda($comp['funcionarios'])?></strong></div><div><span>Fornecedores recorrentes</span><strong><?=formatarMoeda($comp['fornecedores'])?></strong></div><div><span>Outros custos fixos</span><strong><?=formatarMoeda($comp['custos_fixos'])?></strong></div></div>
<div class="grade-dupla" style="margin-top:20px">
<div class="cartao"><h3>Perfil do negócio</h3><p class="secao-ajuda">Nicho não pode ser alterado após o cadastro, mas você pode atualizar a forma de operação e o foco atual.</p><form action="../actions/negocio.php" method="POST" autocomplete="off"><?=csrfCampo()?><input type="hidden" name="acao" value="perfil"><div class="form-grupo"><label>Nicho</label><input value="<?=limpar($usuario['nicho']??'')?>" disabled></div><div class="form-grupo"><label>Nome do negócio</label><input name="nome_negocio" value="<?=limpar($perfil['nome_negocio']??'')?>"></div><div class="form-linha"><div class="form-grupo"><label>Oferta</label><select name="oferta"><?php foreach(['produtos'=>'Produtos','servicos'=>'Serviços','ambos'=>'Produtos e serviços'] as $v=>$l):?><option value="<?=$v?>" <?=($perfil['oferta']??'servicos')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="form-grupo"><label>Operação</label><select name="operacao"><?php foreach(['presencial'=>'Presencial','online'=>'Online','hibrido'=>'Híbrido'] as $v=>$l):?><option value="<?=$v?>" <?=($perfil['operacao']??'presencial')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div></div><div class="form-grupo"><label>Público-alvo</label><input name="publico_alvo" value="<?=limpar($perfil['publico_alvo']??'')?>"></div><div class="form-linha"><div class="form-grupo"><label>Canal principal</label><input name="canal_principal" value="<?=limpar($perfil['canal_principal']??'')?>"></div><div class="form-grupo"><label>Objetivo atual</label><input name="objetivo_principal" value="<?=limpar($perfil['objetivo_principal']??'')?>"></div></div><button class="btn btn-primario">Salvar perfil</button></form></div>
<div class="cartao"><h3>Como os dados se conectam</h3><div class="fluxo-negocio"><span>Vendas</span><b>→</b><span>Receitas</span><b>→</b><span>Dashboard</span><b>→</b><span>RadarPilot</span><b>→</b><span>Copiloto</span></div><p class="secao-ajuda">Funcionários e custos recorrentes entram automaticamente nas despesas do mês. Fornecedores podem ser recorrentes ou pontuais.</p></div>
</div>
<div class="negocio-secoes">
<section class="cartao"><div class="radar-titulo"><div><span class="eyebrow">OFERTA</span><h3>Produtos e serviços</h3></div><span class="radar-badge"><?=count($itens)?> cadastrados</span></div><form action="../actions/negocio.php" method="POST" autocomplete="off" class="form-compacto"><?=csrfCampo()?><input type="hidden" name="acao" value="adicionar_item"><div class="form-linha"><div class="form-grupo"><label>Nome</label><input name="nome" required></div><div class="form-grupo"><label>Tipo</label><select name="tipo"><option value="servico">Serviço</option><option value="produto">Produto</option></select></div></div><div class="form-linha"><div class="form-grupo"><label>Preço de venda</label><input type="number" step="0.01" min="0" name="preco_venda" required></div><div class="form-grupo"><label>Custo unitário/execução</label><input type="number" step="0.01" min="0" name="custo_unitario" value="0"></div></div><button class="btn btn-primario btn-bloco">Adicionar item</button></form><div class="lista-negocio"><?php foreach($itens as $i):?><div class="lista-negocio-item"><div><strong><?=limpar($i['nome'])?></strong><small><?=ucfirst($i['tipo'])?> · venda <?=formatarMoeda((float)$i['preco_venda'])?> · custo <?=formatarMoeda((float)$i['custo_unitario'])?></small></div><form action="../actions/negocio.php" method="POST"><?=csrfCampo()?><input type="hidden" name="acao" value="remover_item"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="excluir-link">Remover</button></form></div><?php endforeach;?></div></section>
<section class="cartao"><div class="radar-titulo"><div><span class="eyebrow">EQUIPE</span><h3>Funcionários</h3></div><span class="radar-badge"><?=count($funcionarios)?> ativos</span></div><p class="secao-ajuda">Ao cadastrar, o custo mensal passa a compor automaticamente as despesas recorrentes.</p><form action="../actions/negocio.php" method="POST" autocomplete="off" class="form-compacto"><?=csrfCampo()?><input type="hidden" name="acao" value="adicionar_funcionario"><div class="form-linha"><div class="form-grupo"><label>Nome</label><input name="nome" required></div><div class="form-grupo"><label>Cargo</label><input name="cargo"></div></div><div class="form-linha"><div class="form-grupo"><label>Salário/base</label><input type="number" step="0.01" min="0" name="salario_base" required></div><div class="form-grupo"><label>Outros custos mensais</label><input type="number" step="0.01" min="0" name="outros_custos" value="0"></div></div><div class="form-grupo"><label>Dia de pagamento</label><input type="number" min="1" max="28" name="dia_pagamento" value="5"></div><button class="btn btn-primario btn-bloco">Adicionar funcionário</button></form><div class="lista-negocio"><?php foreach($funcionarios as $f):?><div class="lista-negocio-item"><div><strong><?=limpar($f['nome'])?></strong><small><?=limpar($f['cargo']??'Sem cargo')?> · <?=formatarMoeda((float)$f['salario_base']+(float)$f['outros_custos'])?>/mês · dia <?=$f['dia_pagamento']?></small></div><form action="../actions/negocio.php" method="POST"><?=csrfCampo()?><input type="hidden" name="acao" value="remover_funcionario"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="excluir-link">Desativar</button></form></div><?php endforeach;?></div></section>
<section class="cartao"><div class="radar-titulo"><div><span class="eyebrow">FORNECEDORES</span><h3>Fornecedores</h3></div><span class="radar-badge"><?=count($fornecedores)?> ativos</span></div><p class="secao-ajuda">Marque como recorrente quando o compromisso acontece todos os meses.</p><form action="../actions/negocio.php" method="POST" autocomplete="off" class="form-compacto"><?=csrfCampo()?><input type="hidden" name="acao" value="adicionar_fornecedor"><div class="form-linha"><div class="form-grupo"><label>Fornecedor</label><input name="nome" required></div><div class="form-grupo"><label>Descrição</label><input name="descricao" placeholder="Ex.: insumos, internet"></div></div><div class="form-linha"><div class="form-grupo"><label>Valor esperado</label><input type="number" step="0.01" min="0" name="valor_padrao" required></div><div class="form-grupo"><label>Dia do vencimento</label><input type="number" min="1" max="28" name="dia_vencimento" value="10"></div></div><label class="check-linha"><input type="checkbox" name="recorrente" value="1"> Cobrança recorrente mensal</label><button class="btn btn-primario btn-bloco">Adicionar fornecedor</button></form><div class="lista-negocio"><?php foreach($fornecedores as $f):?><div class="lista-negocio-item"><div><strong><?=limpar($f['nome'])?></strong><small><?=formatarMoeda((float)$f['valor_padrao'])?> · <?=$f['recorrente']?'recorrente':'pontual'?></small></div><form action="../actions/negocio.php" method="POST"><?=csrfCampo()?><input type="hidden" name="acao" value="remover_fornecedor"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="excluir-link">Desativar</button></form></div><?php endforeach;?></div></section>
<section class="cartao"><div class="radar-titulo"><div><span class="eyebrow">OPERAÇÃO</span><h3>Outros custos</h3></div><span class="radar-badge"><?=count($custos)?> ativos</span></div><p class="secao-ajuda">Registre aluguel, sistemas, marketing e outros custos sem misturar com funcionários.</p><form action="../actions/negocio.php" method="POST" autocomplete="off" class="form-compacto"><?=csrfCampo()?><input type="hidden" name="acao" value="adicionar_custo"><div class="form-grupo"><label>Descrição</label><input name="descricao" required></div><div class="form-linha"><div class="form-grupo"><label>Valor</label><input type="number" step="0.01" min="0.01" name="valor" required></div><div class="form-grupo"><label>Dia do vencimento</label><input type="number" min="1" max="28" name="dia_vencimento" value="10"></div></div><label class="check-linha"><input type="checkbox" name="recorrente" value="1" checked> Custo recorrente mensal</label><button class="btn btn-primario btn-bloco">Adicionar custo</button></form><div class="lista-negocio"><?php foreach($custos as $c):?><div class="lista-negocio-item"><div><strong><?=limpar($c['descricao'])?></strong><small><?=formatarMoeda((float)$c['valor'])?> · <?=$c['recorrente']?'recorrente':'pontual'?></small></div><form action="../actions/negocio.php" method="POST"><?=csrfCampo()?><input type="hidden" name="acao" value="remover_custo"><input type="hidden" name="id" value="<?=$c['id']?>"><button class="excluir-link">Desativar</button></form></div><?php endforeach;?></div></section>
</div>
<?php require_once __DIR__.'/../includes/footer.php';?>
