<?php
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../database/conexao.php';exigirLogin();$tituloPagina='Meu perfil';$pdo=conectar();$uid=usuarioLogadoId();
$stmt=$pdo->prepare('SELECT nome,email,telefone,tipo_perfil,nicho,data_cadastro,avatar_path,limite_gastos_mensal FROM usuarios WHERE id=:uid');$stmt->execute(['uid'=>$uid]);$usuario=$stmt->fetch();$_SESSION['usuario_avatar']=$usuario['avatar_path']??'';$msg=$_SESSION['mensagem_perfil']??null;unset($_SESSION['mensagem_perfil']);$avatar=$usuario['avatar_path']??'';$iniciais='';foreach(preg_split('/\s+/',trim($usuario['nome'])) as $p){if($p!=='')$iniciais.=mb_strtoupper(mb_substr($p,0,1));if(mb_strlen($iniciais)>=2)break;}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/navbar.php';
?>
<div class="topo-pagina"><div><h1>Meu perfil</h1><p>Dados pessoais, segurança e organização da sua conta.</p></div></div><?php if($msg):?><div class="alerta-mensagem sucesso"><?=limpar($msg)?></div><?php endif;?>
<div class="perfil-cabecalho cartao"><div class="perfil-identidade"><?php if($avatar):?><img class="avatar avatar-grande" src="../<?=limpar($avatar)?>" alt="Foto de perfil"><?php else:?><span class="avatar avatar-grande avatar-iniciais"><?=limpar($iniciais?:'CP')?></span><?php endif;?><div><h2><?=limpar($usuario['nome'])?></h2><p><?=$usuario['tipo_perfil']==='mei'?'Empreendedor':'Pessoa física'?><?=$usuario['nicho']?' · '.limpar($usuario['nicho']):''?></p></div></div><form action="../actions/perfil.php" method="POST" enctype="multipart/form-data" class="avatar-form" autocomplete="off"><?=csrfCampo()?><input type="hidden" name="acao" value="upload_avatar"><input type="file" name="avatar" id="avatar" accept="image/jpeg,image/png,image/webp" hidden onchange="this.form.submit()"><label for="avatar" class="btn btn-secundario">Alterar foto</label></form></div>
<div class="grade-dupla perfil-grid"><div class="cartao"><h3>Dados pessoais</h3><p class="secao-ajuda">Você pode alterar seus dados de contato. Tipo de conta e nicho ficam bloqueados após o cadastro.</p><form action="../actions/perfil.php" method="POST" autocomplete="off"><?=csrfCampo()?><input type="hidden" name="acao" value="atualizar_dados"><div class="form-grupo"><label for="nome">Nome</label><input autocomplete="off" type="text" id="nome" name="nome" required value="<?=limpar($usuario['nome'])?>"></div><div class="form-linha"><div class="form-grupo"><label for="email">E-mail</label><input autocomplete="off" type="email" id="email" name="email" required value="<?=limpar($usuario['email'])?>"></div><div class="form-grupo"><label for="telefone">Telefone</label><input autocomplete="off" type="tel" id="telefone" name="telefone" value="<?=limpar($usuario['telefone']??'')?>"></div></div><div class="form-linha"><div class="form-grupo"><label>Tipo de conta</label><input value="<?=$usuario['tipo_perfil']==='mei'?'Empreendedor':'Pessoa física'?>" disabled></div><?php if($usuario['tipo_perfil']==='mei'):?><div class="form-grupo"><label>Nicho do negócio</label><input value="<?=limpar($usuario['nicho']??'')?>" disabled></div><?php else:?><div class="form-grupo"><label for="limite_gastos_mensal">Limite mensal de gastos</label><input autocomplete="off" type="number" step="0.01" min="0" id="limite_gastos_mensal" name="limite_gastos_mensal" value="<?=limpar((string)($usuario['limite_gastos_mensal']??''))?>" placeholder="Opcional"></div><?php endif;?></div><button type="submit" class="btn btn-primario">Salvar dados</button></form></div>
<div class="cartao"><h3>Organização e dados</h3><p class="secao-ajuda">Recursos administrativos que não precisam ocupar a navegação principal.</p><div class="perfil-links"><a href="contas.php" class="perfil-link"><span>◫</span><div><strong>Contas</strong><small>Contas e carteiras.</small></div></a><a href="importar.php" class="perfil-link"><span>⇧</span><div><strong>Importar extrato</strong><small>Adicione movimentações via CSV.</small></div></a><a href="importacoes.php" class="perfil-link"><span>◷</span><div><strong>Importações</strong><small>Histórico de extratos.</small></div></a><a href="categorias.php" class="perfil-link"><span>◇</span><div><strong>Categorias</strong><small>Organize classificações.</small></div></a><?php if($usuario['tipo_perfil']==='mei'):?><a href="negocio.php" class="perfil-link"><span>▣</span><div><strong>Estrutura do negócio</strong><small>Produtos, serviços e funcionários.</small></div></a><?php endif;?><a href="../actions/exportar.php?token=<?=urlencode(csrfToken())?>" class="perfil-link"><span>↓</span><div><strong>Exportar dados</strong><small>Baixe receitas e despesas em CSV.</small></div></a></div></div></div>
<div class="cartao perfil-seguranca"><div class="perfil-seguranca-topo"><div><h3>Segurança</h3><p class="secao-ajuda">A alteração de senha fica isolada das demais informações.</p></div><button type="button" class="btn btn-secundario" id="mostrarSenha">Alterar senha</button></div><div id="painelSenha" class="senha-painel" hidden><form action="../actions/perfil.php" method="POST" autocomplete="off"><?=csrfCampo()?><input type="hidden" name="acao" value="alterar_senha"><div class="form-linha"><div class="form-grupo"><label for="senha_atual">Senha atual</label><input autocomplete="off" type="password" id="senha_atual" name="senha_atual" required></div><div class="form-grupo"><label for="senha_nova">Nova senha</label><input autocomplete="off" type="password" id="senha_nova" name="senha_nova" required minlength="6"></div></div><button type="submit" class="btn btn-primario">Salvar nova senha</button></form></div></div>
<div class="perfil-zona-saida"><a href="../actions/logout.php" class="btn btn-perigo">Sair da conta</a></div>
<script>document.getElementById('mostrarSenha').addEventListener('click',function(){const p=document.getElementById('painelSenha');p.hidden=!p.hidden;this.textContent=p.hidden?'Alterar senha':'Fechar';});</script>
<?php require_once __DIR__.'/../includes/footer.php';?>
