<?php
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../database/conexao.php';exigirLogin();
$tituloPagina='Relatórios';$pdo=conectar();$usuarioId=usuarioLogadoId();$empreendedor=usuarioLogadoTipo()==='mei';$periodo=(int)($_GET['periodo']??1);if(!in_array($periodo,[1,3,6,12],true))$periodo=1;$inicio=date('Y-m-01',strtotime('-'.($periodo-1).' months'));$fim=date('Y-m-t');
function executarPythonRel(string $script,array $args):?array{$pasta=escapeshellarg(__DIR__.'/../python');$python=PHP_OS_FAMILY==='Windows'?'python':'python3';$cmd='cd '.$pasta.' && '.$python.' '.escapeshellarg($script);foreach($args as $a)$cmd.=' '.escapeshellarg((string)$a);$cmd.=' 2>/dev/null';$saida=@shell_exec($cmd);$d=json_decode($saida??'',true);return is_array($d)?$d:null;}
$res=executarPythonRel('analise.py',[$usuarioId,$periodo]);$evolucaoMensal=$res['evolucao_mensal']??[];
if(empty($evolucaoMensal)){for($i=$periodo-1;$i>=0;$i--){$ref=new DateTime("first day of -{$i} month");$ri=$ref->format('Y-m-01');$rf=$ref->format('Y-m-t');$a=$pdo->prepare('SELECT COALESCE(SUM(valor),0) FROM receitas WHERE usuario_id=:uid AND data_receita BETWEEN :i AND :f');$a->execute(['uid'=>$usuarioId,'i'=>$ri,'f'=>$rf]);$r=(float)$a->fetchColumn();$a=$pdo->prepare('SELECT COALESCE(SUM(valor),0) FROM despesas WHERE usuario_id=:uid AND data_despesa BETWEEN :i AND :f');$a->execute(['uid'=>$usuarioId,'i'=>$ri,'f'=>$rf]);$d=(float)$a->fetchColumn();$evolucaoMensal[]=['mes'=>$ref->format('Y-m'),'receitas'=>$r,'despesas'=>$d];}}
function categoriasRel(PDO $pdo,string $tabela,string $campo,int $uid,string $i,string $f):array{$s=$pdo->prepare("SELECT COALESCE(c.nome,'Outros') categoria,COALESCE(SUM(x.valor),0) total FROM {$tabela} x LEFT JOIN categorias c ON c.id=x.categoria_id WHERE x.usuario_id=:uid AND x.{$campo} BETWEEN :i AND :f GROUP BY categoria ORDER BY total DESC");$s->execute(['uid'=>$uid,'i'=>$i,'f'=>$f]);return $s->fetchAll();}
$gastos=categoriasRel($pdo,'despesas','data_despesa',$usuarioId,$inicio,$fim);$entradas=categoriasRel($pdo,'receitas','data_receita',$usuarioId,$inicio,$fim);$receitasPeriodo=array_sum(array_map('floatval',array_column($entradas,'total')));$despesasPeriodo=array_sum(array_map('floatval',array_column($gastos,'total')));$maiorCategoria=$gastos[0]??null;$origemRenda=$entradas[0]??null;$resultado=$receitasPeriodo-$despesasPeriodo;
$stmt=$pdo->prepare('SELECT descricao,SUM(valor) total,COUNT(*) ocorrencias FROM despesas WHERE usuario_id=:uid AND data_despesa>=:inicio GROUP BY descricao HAVING COUNT(*)>=2 ORDER BY total DESC LIMIT 1');$stmt->execute(['uid'=>$usuarioId,'inicio'=>$inicio]);$gastoRecorrente=$stmt->fetch();
$leitura=[];$leitura[]=$resultado>=0?'O período terminou com resultado positivo de '.formatarMoeda($resultado).'.':'O período terminou com resultado negativo de '.formatarMoeda(abs($resultado)).'.';if($maiorCategoria&&$despesasPeriodo>0){$pct=((float)$maiorCategoria['total']/$despesasPeriodo)*100;$leitura[]=$maiorCategoria['categoria'].' concentra '.number_format($pct,1,',','.').'% das despesas do período.';}if($origemRenda&&$receitasPeriodo>0){$pct=((float)$origemRenda['total']/$receitasPeriodo)*100;$leitura[]=$origemRenda['categoria'].' representa '.number_format($pct,1,',','.').'% das entradas.';}
?>
<?php require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/navbar.php'; ?>
<div class="topo-pagina"><div><h1>Relatórios</h1><p><?= $empreendedor ? 'Aprofunde faturamento, custos e resultado sem confundir relatório com o dashboard operacional.' : 'Transforme seus números em uma leitura simples do seu comportamento financeiro.' ?></p></div><div class="periodos-grafico rel-periodos"><?php foreach([1=>'1M',3=>'3M',6=>'6M',12=>'12M'] as $m=>$label):?><a href="relatorios.php?periodo=<?=$m?>" class="periodo <?=$periodo===$m?'ativo':''?>"><?=$label?></a><?php endforeach;?></div></div>
<div class="grade-resumo"><div class="cartao cartao-metrica"><div class="rotulo"><?= $empreendedor ? 'Maior origem de faturamento' : 'Maior origem de renda' ?></div><div class="valor positivo" style="font-size:20px"><?=limpar($origemRenda['categoria']??'Sem dados')?></div><?php if($origemRenda):?><div class="variacao"><?=formatarMoeda((float)$origemRenda['total'])?> no período</div><?php endif;?></div><div class="cartao cartao-metrica"><div class="rotulo">Maior categoria de gasto</div><div class="valor negativo" style="font-size:20px"><?=limpar($maiorCategoria['categoria']??'Sem dados')?></div><?php if($maiorCategoria):?><div class="variacao"><?=formatarMoeda((float)$maiorCategoria['total'])?> no período</div><?php endif;?></div><div class="cartao cartao-metrica"><div class="rotulo">Gasto recorrente</div><div class="valor negativo" style="font-size:20px"><?=limpar($gastoRecorrente['descricao']??'Nenhum identificado')?></div><?php if($gastoRecorrente):?><div class="variacao"><?=(int)$gastoRecorrente['ocorrencias']?> ocorrências · <?=formatarMoeda((float)$gastoRecorrente['total'])?></div><?php endif;?></div></div>
<div class="grade-dupla"><div class="cartao"><div class="cabecalho-grafico"><div><h3><?= $empreendedor ? 'Faturamento x Despesas' : 'Receitas x Despesas' ?></h3><p class="secao-ajuda">Evolução do período selecionado.</p></div></div><div class="container-grafico"><canvas id="graficoEvolucaoRelatorio"></canvas></div></div><div class="cartao"><div class="cabecalho-grafico"><div><h3>Distribuição</h3><p class="secao-ajuda">Escolha se quer analisar entradas ou gastos.</p></div><div class="periodos-grafico"><button type="button" class="rel-tipo ativo" data-tipo="gastos">Gastos</button><button type="button" class="rel-tipo" data-tipo="entradas">Entradas</button></div></div><div class="container-grafico" style="height:260px"><canvas id="graficoCategorias"></canvas></div></div></div>
<div class="grade-dupla" style="margin-top:20px"><div class="cartao"><h3 style="margin-bottom:16px">Detalhamento</h3><div class="rel-detalhes" id="relDetalhes"></div></div><div class="cartao"><div class="radar-titulo"><div><h3>O que esses dados mostram?</h3><p class="secao-ajuda">Uma leitura rápida antes de aprofundar a análise.</p></div><button type="button" class="btn btn-secundario" data-copiloto-pergunta="Explique meu relatório dos últimos <?=$periodo?> mês(es) e indique o ponto que mais merece atenção.">Perguntar ao Copiloto</button></div><div class="rel-leitura"><?php foreach($leitura as $linha):?><p>• <?=limpar($linha)?></p><?php endforeach;?></div></div></div>
<script src="../assets/js/dashboard.js"></script><script src="../assets/js/relatorios.js"></script><script>const dadosEvolucao=<?=json_encode($evolucaoMensal,JSON_UNESCAPED_UNICODE)?>;const dadosGastos=<?=json_encode($gastos,JSON_UNESCAPED_UNICODE)?>;const dadosEntradas=<?=json_encode($entradas,JSON_UNESCAPED_UNICODE)?>;inicializarGraficoEvolucao(dadosEvolucao,'graficoEvolucaoRelatorio');inicializarGraficoCategorias(dadosGastos);inicializarRelatorioAlternancia(dadosGastos,dadosEntradas);</script>
<?php require_once __DIR__.'/../includes/footer.php'; ?>
