<?php
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../database/conexao.php';
require_once __DIR__.'/../includes/negocio_financeiro.php';
exigirLogin();validarCsrf();if(usuarioLogadoTipo()!=='mei'){header('Location: ../pages/dashboard.php');exit;}
$pdo=conectar();$uid=usuarioLogadoId();$acao=$_POST['acao']??'';
function cpNumero($v):float{return max(0,(float)str_replace(',','.',(string)$v));}
try{
if($acao==='perfil'){$oferta=in_array($_POST['oferta']??'',['produtos','servicos','ambos'],true)?$_POST['oferta']:'servicos';$operacao=in_array($_POST['operacao']??'',['presencial','online','hibrido'],true)?$_POST['operacao']:'presencial';$s=$pdo->prepare('INSERT INTO perfil_negocio (usuario_id,nome_negocio,oferta,operacao,publico_alvo,canal_principal,objetivo_principal) VALUES (:uid,:nome,:oferta,:operacao,:publico,:canal,:objetivo) ON DUPLICATE KEY UPDATE nome_negocio=VALUES(nome_negocio),oferta=VALUES(oferta),operacao=VALUES(operacao),publico_alvo=VALUES(publico_alvo),canal_principal=VALUES(canal_principal),objetivo_principal=VALUES(objetivo_principal)');$s->execute(['uid'=>$uid,'nome'=>trim($_POST['nome_negocio']??'')?:null,'oferta'=>$oferta,'operacao'=>$operacao,'publico'=>trim($_POST['publico_alvo']??'')?:null,'canal'=>trim($_POST['canal_principal']??'')?:null,'objetivo'=>trim($_POST['objetivo_principal']??'')?:null]);}
if($acao==='adicionar_item'){$nome=trim($_POST['nome']??'');$tipo=($_POST['tipo']??'')==='produto'?'produto':'servico';if($nome!==''){$s=$pdo->prepare('INSERT INTO produtos_servicos (usuario_id,nome,tipo,preco_venda,custo_unitario) VALUES (:uid,:nome,:tipo,:preco,:custo)');$s->execute(['uid'=>$uid,'nome'=>$nome,'tipo'=>$tipo,'preco'=>cpNumero($_POST['preco_venda']??0),'custo'=>cpNumero($_POST['custo_unitario']??0)]);}}
if($acao==='remover_item'){$s=$pdo->prepare('UPDATE produtos_servicos SET ativo=0 WHERE id=:id AND usuario_id=:uid');$s->execute(['id'=>(int)($_POST['id']??0),'uid'=>$uid]);}
if($acao==='adicionar_funcionario'){$nome=trim($_POST['nome']??'');if($nome!==''){$s=$pdo->prepare('INSERT INTO funcionarios (usuario_id,nome,cargo,salario_base,outros_custos,dia_pagamento) VALUES (:uid,:nome,:cargo,:salario,:custos,:dia)');$s->execute(['uid'=>$uid,'nome'=>$nome,'cargo'=>trim($_POST['cargo']??'')?:null,'salario'=>cpNumero($_POST['salario_base']??0),'custos'=>cpNumero($_POST['outros_custos']??0),'dia'=>max(1,min(28,(int)($_POST['dia_pagamento']??5)))]);cpSincronizarCustosRecorrentesMes($pdo,$uid);}}
if($acao==='remover_funcionario'){$id=(int)($_POST['id']??0);$s=$pdo->prepare('UPDATE funcionarios SET ativo=0 WHERE id=:id AND usuario_id=:uid');$s->execute(['id'=>$id,'uid'=>$uid]);}
if($acao==='adicionar_fornecedor'){$nome=trim($_POST['nome']??'');$valor=cpNumero($_POST['valor_padrao']??0);$rec=!empty($_POST['recorrente'])?1:0;if($nome!==''){$s=$pdo->prepare('INSERT INTO fornecedores (usuario_id,nome,descricao,valor_padrao,recorrente,dia_vencimento) VALUES (:uid,:nome,:descricao,:valor,:rec,:dia)');$s->execute(['uid'=>$uid,'nome'=>$nome,'descricao'=>trim($_POST['descricao']??'')?:null,'valor'=>$valor,'rec'=>$rec,'dia'=>max(1,min(28,(int)($_POST['dia_vencimento']??10)))]);$id=(int)$pdo->lastInsertId();if($rec){cpSincronizarCustosRecorrentesMes($pdo,$uid);}elseif($valor>0){$cat=cpCategoriaId($pdo,$uid,'Fornecedores','despesa');$d=$pdo->prepare('INSERT INTO despesas (usuario_id,categoria_id,valor,descricao,data_despesa,origem_tipo,origem_id) VALUES (:uid,:cat,:valor,:descricao,:data,"fornecedor",:oid)');$d->execute(['uid'=>$uid,'cat'=>$cat,'valor'=>$valor,'descricao'=>'Fornecedor · '.$nome,'data'=>date('Y-m-d'),'oid'=>$id]);}}}
if($acao==='remover_fornecedor'){$s=$pdo->prepare('UPDATE fornecedores SET ativo=0 WHERE id=:id AND usuario_id=:uid');$s->execute(['id'=>(int)($_POST['id']??0),'uid'=>$uid]);}
if($acao==='adicionar_custo'){$descricao=trim($_POST['descricao']??'');$valor=cpNumero($_POST['valor']??0);$rec=!empty($_POST['recorrente'])?1:0;if($descricao!==''&&$valor>0){$s=$pdo->prepare('INSERT INTO custos_negocio (usuario_id,descricao,valor,recorrente,dia_vencimento) VALUES (:uid,:descricao,:valor,:rec,:dia)');$s->execute(['uid'=>$uid,'descricao'=>$descricao,'valor'=>$valor,'rec'=>$rec,'dia'=>max(1,min(28,(int)($_POST['dia_vencimento']??10)))]);$id=(int)$pdo->lastInsertId();if($rec){cpSincronizarCustosRecorrentesMes($pdo,$uid);}else{$cat=cpCategoriaId($pdo,$uid,'Custos fixos','despesa');$d=$pdo->prepare('INSERT INTO despesas (usuario_id,categoria_id,valor,descricao,data_despesa,origem_tipo,origem_id) VALUES (:uid,:cat,:valor,:descricao,:data,"custo_fixo",:oid)');$d->execute(['uid'=>$uid,'cat'=>$cat,'valor'=>$valor,'descricao'=>'Custo · '.$descricao,'data'=>date('Y-m-d'),'oid'=>$id]);}}}
if($acao==='remover_custo'){$s=$pdo->prepare('UPDATE custos_negocio SET ativo=0 WHERE id=:id AND usuario_id=:uid');$s->execute(['id'=>(int)($_POST['id']??0),'uid'=>$uid]);}
$_SESSION['mensagem_negocio']='Informações atualizadas com sucesso.';
}catch(Throwable $e){error_log('CashPilot/Negocio: '.$e->getMessage());$_SESSION['mensagem_negocio']='Não foi possível salvar. Confirme se a migration do CashPilot 7 foi executada.';}
header('Location: ../pages/negocio.php');exit;
